/**
 * AIRequestBuilder Service (Phase 5 — Component 1)
 *
 * Responsibility ONLY:
 * - Read Runtime Resolver output
 * - Inject dynamic variables into prompt tokens ({{variable_name}})
 * - Merge modular Prompt Sections (System instruction, Rules, Verification guidelines)
 * - Attach required structural Output Schema specifications
 * - Build Final Prompt string and standardized conversation messages array
 * - Create canonical Provider Payload ready for ProviderManager execution
 * - Compute deterministic SHA-256 cache fingerprint (Component 15)
 *
 * IMPORTANT ARCHITECTURE RULE:
 * The Groq Manager (or any other provider driver) must NEVER build or concatenate prompts!
 * The Request Builder is the ONLY location where prompts are compiled in Code-A-Nova.
 */

const runtimeLogger = require("./RuntimeLogger");

class AIRequestBuilder {
  /**
   * Builds the comprehensive provider execution payload from resolver and runtime contexts.
   * @param {Object} params
   * @param {Object} params.resolverOutput - Output generated by RuntimeResolver.resolveBlueprintAssignment or resolveRuntimePreview
   * @param {Object} params.runtimeProviderConfig - Hierarchical configuration from AssessmentRuntimeConfig
   * @param {Object} params.dynamicVariables - Runtime variable overrides passed at execution time (e.g., from Assessment Session or Admin Test)
   * @param {Object} params.options - Optional flags like streaming, maxTokens override, custom timeout
   */
  buildRequestPayload({
    resolverOutput = {},
    runtimeProviderConfig = {},
    dynamicVariables = {},
    options = {}
  }) {
    const startTime = Date.now();

    // 1. Extract blueprint baseline and fallback structures
    const blueprint = resolverOutput.selectedBlueprint || resolverOutput.blueprint || {};
    const blueprintVersion = blueprint.activeVersion || resolverOutput.blueprint?.activeVersion || 1;
    
    // 2. Merge Variables (Library defaults -> Blueprint variables -> Dynamic runtime overrides)
    const baseVariables = resolverOutput.resolvedVariables || {};
    const finalVariables = { ...baseVariables, ...dynamicVariables };

    // Ensure common canonical fallback variable values exist if unassigned
    if (!finalVariables.questionCount && !finalVariables.question_count) finalVariables.questionCount = "5";
    if (!finalVariables.difficulty) finalVariables.difficulty = "Medium";
    if (!finalVariables.language) finalVariables.language = "English";

    // 3. Extract and Merge Prompt Sections
    let systemInstruction = blueprint.systemInstruction || resolverOutput.resolvedPrompt?.systemInstruction || "You are a senior principal AI technical evaluator and examination architect at Code-A-Nova. Generate high-quality technical assessment questions.";
    let generationRules = blueprint.rules || resolverOutput.resolvedPrompt?.rules || "1. Generate exactly {{questionCount}} high-fidelity items matching difficulty tier.\n2. Ensure zero textual duplication or conversational introduction.";
    let additionalContext = blueprint.context || resolverOutput.resolvedPrompt?.context || "Target candidate assessment execution.";

    // 4. Attach Output Schema Specification
    const defaultMCQSchema = `[
  {
    "questionText": "Clear, detailed technical question...",
    "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
    "correctIndex": 0,
    "explanation": "Detailed explanation of why the correct option is right and others are wrong.",
    "difficulty": "Medium",
    "tags": ["category1", "category2"]
  }
]`;
    const outputSchemaObj = resolverOutput.selectedSchema || blueprint.outputSchema || {};
    let schemaString = outputSchemaObj.jsonSchemaString || (typeof outputSchemaObj === "string" ? outputSchemaObj : JSON.stringify(outputSchemaObj, null, 2));
    if (!schemaString || schemaString === "{}" || schemaString === "[]") {
      schemaString = defaultMCQSchema;
    }
    const expectedFormat = outputSchemaObj.expectedResponseFormat || outputSchemaObj.name || "JSON Array of Questions";

    const schemaInstruction = `\n\n### MANDATORY JSON OUTPUT SCHEMA DIRECTIVE ###\nYou MUST respond STRICTLY with a valid JSON string conforming exactly to the following structure (${expectedFormat}). Do NOT wrap the JSON in markdown code blocks or provide explanatory conversational text before or after the JSON:\n${schemaString}`;

    // 5. Inject Variables into all prompt blocks
    const injectToken = (text) => {
      if (typeof text !== "string") return "";
      return text.replace(/\{\{\s*([a-zA-Z0-9_-]+)\s*\}\}/g, (match, key) => {
        // Look up by direct key, camelCase, or snake_case conversion
        if (finalVariables[key] !== undefined) return String(finalVariables[key]);
        const camel = key.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
        if (finalVariables[camel] !== undefined) return String(finalVariables[camel]);
        return match; // Retain token if variable unsupplied
      });
    };

    const compiledSystem = injectToken(systemInstruction);
    const compiledRules = injectToken(generationRules);
    const compiledContext = injectToken(additionalContext);
    const compiledSchema = injectToken(schemaInstruction);

    // Merge into complete master system prompt
    const finalSystemPrompt = `${compiledSystem}\n\n### CONTEXT ###\n${compiledContext}\n\n### EVALUATION RULES ###\n${compiledRules}${compiledSchema}`;

    // Construct User Prompt triggering execution
    const customUserTrigger = options.customUserPrompt || `Generate an assessment evaluation batch adhering strictly to the above blueprint configuration, rules, and JSON schema format for category: ${finalVariables.category || "Technical Assessment"} (${finalVariables.subcategory || "General"}).`;
    const finalUserPrompt = injectToken(customUserTrigger);

    // 6. Assemble standard conversational messages array
    const messages = [
      { role: "system", content: finalSystemPrompt },
      { role: "user", content: finalUserPrompt }
    ];

    // 7. Extract Provider Parameters from hierarchical configuration
    const targetProvider = runtimeProviderConfig.primaryProvider || options.provider || "Groq";
    const targetModel = runtimeProviderConfig.modelName || options.model || "llama-3.1-8b-instant";
    const temperature = runtimeProviderConfig.temperature !== undefined ? runtimeProviderConfig.temperature : 0.65;
    const topP = runtimeProviderConfig.topP !== undefined ? runtimeProviderConfig.topP : 0.9;
    const maxTokens = runtimeProviderConfig.maxTokens || options.maxTokens || 2500;
    const timeoutMs = runtimeProviderConfig.requestTimeoutMs || options.timeoutMs || 7000; // Strict 7s SLA boundary
    const fallbackProviders = runtimeProviderConfig.fallbackProviders || ["OpenAI", "Gemini"];

    // 8. Compute Cache Fingerprint (Component 15)
    const fingerprint = runtimeLogger.generateRequestFingerprint({
      blueprintVersion,
      variables: finalVariables,
      outputSchema: schemaString,
      provider: targetProvider,
      model: targetModel
    });

    // Token estimation baseline (~1 token per 4 chars)
    const totalChars = finalSystemPrompt.length + finalUserPrompt.length;
    const estimatedTokens = Math.ceil(totalChars / 3.8);

    const buildTimeMs = Date.now() - startTime;

    // 9. Build final complete Request Payload for ProviderManager
    const providerPayload = {
      requestId: options.requestId || runtimeLogger.generateRequestId(),
      targetProvider,
      targetModel,
      fallbackProviders,
      temperature,
      topP,
      maxTokens,
      timeoutMs,
      streamingEnabled: Boolean(options.streamingEnabled || runtimeProviderConfig.streamingEnabled),
      responseFormat: { type: "json_object" },
      messages,
      fingerprint,
      meta: {
        blueprintId: blueprint._id || blueprint.id || null,
        blueprintName: blueprint.name || "Canonical Standard Blueprint",
        blueprintVersion,
        assessmentConfigVersion: resolverOutput.config?.version || 1,
        expectedFormat,
        jsonSchemaSpecification: schemaString,
        injectedVariablesCount: Object.keys(finalVariables).length,
        estimatedPromptTokens: estimatedTokens,
        builderLatencyMs: buildTimeMs
      }
    };

    return providerPayload;
  }
}

module.exports = new AIRequestBuilder();
